# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install .[docs]
    - sphinx-build -c docs docs/source $READTHEDOCS_OUTPUT/html/
